### ISSUE TITLE
Could you share the two crowd scene datasets in your paper?

### ISSUE THREAD

**Issue by gjy3035** [xialeiliu/CrowdCounting_cvpr18#4]
Hi, thanks for your awesome work! I am very interested in the two unlabeled datasets collected by you in the paper.

**Comment by shz1314** [comment]
@gjy3035 您有制作好的数据集吗  可以分享吗  我制作了几天实在头痛 如果能分享万分感谢。

**Comment by gjy3035** [comment]
@shz1314 你是需要生成好的密度图吗？这里有GT的生成工具。其中MATLAB要比Python的代码速度快很多。
https://github.com/gjy3035/Awesome-Crowd-Counting#tools

由于密度图必须无损，所以占用空间太大，给你分享也不太现实，你可以先试试这个工具

**Comment by 2hip3ng** [comment]
请问可以分享一下没有标注的数据集吗？@gjy3035

**Comment by gjy3035** [comment]
@2hip3ng 抱歉，这个数据我也没有。

**Comment by xialeiliu** [comment]
We will not resealse the dataset for now because we don't filter the images with proper content, some images might contain violent scene, etc. We would suggest you to download images from google if you really need them, there are tools downloading images. Another way you could do is to use another dataset as unlabeled dataset, which should perform the similar.

Thanks for your interest again. Sorry for the inconvenient.
