### ISSUE TITLE
Unlabeled Dataset

### ISSUE THREAD

**Issue by 2hip3ng** [xialeiliu/CrowdCounting_cvpr18#6]
Can you share the Unlabeled Dataset? Not the gt dataset. The dataset you collected from google.

**Comment by xialeiliu** [comment]
We will not resealse the dataset for now because we don't filter the images with proper content, some images might contain violent scene, etc. We would suggest you to download images from google if you really need them, there are tools downloading images. Another way you could do is to use another dataset as unlabeled dataset, which should perform the similar.

Thanks for your interest again. Sorry about the inconvenient.

**Comment by Viresh-R** [comment]
Hey,
Would it be possible to share the image links instead, rather than sharing the images directly ? I don't think you would need any copyrights for sharing the image links.

Thanks !
